FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"
SRC_URI += "file://witherspoon.cfg"
SRC_URI += "file://0001-misc-Add-MCTP-LPC-driver-for-ASPEED-KCS-devices.patch"
SRC_URI += "file://0002-mctp-lpc-Emit-an-error-on-overrun.patch"
SRC_URI += "file://0003-mctp-lpc-Leave-value-in-IDR-and-disable-IRQ-on-IRQ.patch"
SRC_URI += "file://0001-mctp-lpc-Retry-writing-ODR-if-OBF-is-not-set.patch"
SRC_URI += "file://0001-mctp-lpc-Synchronise-IDR-ODR-accesses-with-IBF-OBF.patch"
